config/routes.rb
Rails.application.routes.draw do
  devise_for :docs
root 'docs#index'

  resources :docs do
    resources :projects
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :doc
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_doc!
  skip_before_action :authenticate_doc!, :only => [:index, :show]
  rescue_from ActiveRecord::RecordNotFound, with: :couldnt_find_record

  private
  def couldnt_find_record
    redirect_to root_url, notice: "That record doesn't exist!"
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  before_action :set_session


  def set_session
    session[:history] ||= []
  end

  def index
    @docs = Doc.all
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = Doc.create!(doc_params.merge(doc: current_doc))
    redirect_to doc_path(@doc), notice: "Documentarian created!"
end

  def show
    @doc = Doc.find(params[:id])
    session[:history].push(@doc.name)
  end

  def edit
    @doc = Doc.find(params[:id])
  end

  def update
    @doc = Doc.find(params[:id])
    if @doc == current_doc
      @doc.update(doc_params)
    else
      flash[:alert] = "Only owner can edit"
    end
    redirect_to doc_path(@doc)
  end

  def destroy
    @doc = Doc.find(params[:id])
    if @doc == current_doc || current_doc.admin?
      @doc.destroy
    else
      flash[:alert] = "Only owner can delete"
    end
    redirect_to docs_path
  end

  private
  def doc_params
    params.require(:doc).permit(:name, :location, :gender, :img_url)

  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @doc = Doc.find(params[:doc_id])
    @project = Project.new
  end

  def create
    @doc = Doc.find(params[:doc_id])
    @project = @doc.projects.create!(project_params)
    redirect_to doc_project_path(@doc, @project), notice: "Story created!"
  end

  def show
    @doc = Doc.find(params[:doc_id])
    @project = Project.find(params[:id])
  end

  def edit
    @doc = Doc.find(params[:doc_id])
    @project = Project.find(params[:id])
  end

  def update
    @doc = Doc.find(params[:doc_id])
    @project = Project.find(params[:id])
    if @project.doc == current_doc
      @project.update!(project_params)
    else
      flash[:alert] = "Only owner can edit"
    end
    redirect_to doc_project_path(@doc, @project)
  end

  def destroy
    @doc = Doc.find(params[:doc_id])
    @project = Project.find(params[:id])
    if @project.doc == current_doc
      @project.destroy
    else
      flash[:alert] = "Only owner can delete"
    end
    redirect_to doc_path(@doc)
  end

  private
  def project_params
    params.require(:project).permit(:title, :theme, :img_url, :body)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/docs/edit.html.erb
<div class="show">

<h1>make changes to your profile here</h1>

<%= form_for @doc do |f| %>
Name: <%= f.text_field :name %>
Base: <%= f.text_field :location %>
Gender: <%= f.text_field :gender %>
Photo: <%= f.text_field :img_url %>
<%= f.submit %>
<% end %>

<h3>delete your profile?</h3>
<%= form_for @doc, method: :delete do |f| %>
<%= f.submit "Delete!", class: "delete" %>
<% end %>

</div>

app/views/docs/index.html.erb
<div class="index">
<h1>Documentarians: </h1>

<h2>Create new <%= link_to"(+)", new_doc_path %> </h2>

  <% @docs.each do |doc| %>
  <h2><%= link_to doc.name, doc %></h2>
  <% if current_doc && current_doc.admin? %>
    | <%= link_to "delete", doc, method: :delete,
                                  data: { confirm: "Delete this user?" } %>
  <% end %>
  <% end %>
</div>

app/views/docs/new.html.erb
<div class="show">

<h1>Create your Doc profile here!</h1>

<%= form_for :doc, url: docs_path do |f| %>
Name: <%= f.text_field :name %>
Base: <%= f.text_field :location %>
Gender: <%= f.text_field :gender %>
Photo: <%= f.text_field :img_url %>
<%= f.submit %>
<% end %>

</div>

app/views/docs/show.html.erb
<div class="show">

  <h1><%= @doc.name %></h1>

  <h2><%= @doc.location %></h2>



<div class="profile">
  <%= image_tag @doc.img_url unless @doc.img_url.blank? %>
</div>

<h2>Stories</h2>
<% @doc.projects.each do |project| %>
    <h3><%= link_to project.title, doc_project_path(@doc, project) %></h3>
<% end %>
</div>

<h3>Add Story<%= link_to "(+)", new_doc_project_path(@doc) %></h3>


<h2><%= link_to "Edit profile?", edit_doc_path(@doc) %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryDoc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab" rel="stylesheet">

  </head>

  <body>
    <div class="static">
      <h1><%= link_to "StoryDoc", root_path %></h1>
      <h3>Home for Documentarians and their Stories.</h3>



      <% flash.each do |type, message| %>
      <p class="flash <%= type %>"><%= message %></p>
      <% end %>

      <div class="hero">
        <%= image_tag("thumb_IMG_2057_1024.jpg") %>
        <%= image_tag("IMG_0260.jpg") %>
        <%= image_tag("IMG_0325.jpg") %>
      </div>

    </div>
    <% if !current_doc %>
      <%= link_to "New to StoryDoc?  Join Here!", new_doc_registration_path %><br>
      <br>
      <%= link_to "Sign in to your StoryDoc account", new_doc_session_path %>
    <% else %>
      <%= link_to "Sign out of StoryDoc", destroy_doc_session_path, :method => :delete %>
        <%= current_doc.email %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<div class="show">


<h2>edit your story here</h2>

<%= form_for [@doc, @project] do |f| %>
    title: <%= f.text_field :title %><br>
    <br>
    theme: <%= f.text_field :theme %><br>
    <br>
    photos: <%= f.text_field :img_url %><br>
    <br>
    body: <%= f.text_area :body, cols: "50", rows: "10" %><br>
    <br>
  <%= f.submit %>
<% end %>


<h3>delete your story?</h3>
<%= form_for [@doc, @project], method: :delete do |f| %>
<%= f.submit "Delete!", class: "delete" %>
<% end %>

</div>

app/views/projects/index.html.erb
<h1>these are the stories.</h1>

<% @projects.each do |project| %>
<%= link_to project.title, project %>
<% end %>

app/views/projects/new.html.erb
<div class="show">



<h1>add your story here.</h1>



<%= form_for [@doc, @project] do |f| %>
    title: <%= f.text_field :title %><br>
    <br>
    theme: <%= f.text_field :theme %><br>
    <br>
    photos: <%= f.text_field :img_url %><br>
    <br>

    <br>
    body: <%= f.text_area :body, cols: "50", rows: "10" %><br>
    <br>
  <%= f.submit %>
<% end %>

</div>

app/views/projects/show.html.erb
<div class="show">



<div>
  <h1><%= @project.title %></h1>

  <h3>by: <%= @project.doc.name %></h>
</div>

<div>
  <h3>theme(s):<%= @project.theme %></h3>
</div>

<div class="gallery">
  <%= image_tag @project.img_url %>
</div>



<div>
  <h2> <%= @project.body %></h2>
</div>



<%= link_to "Edit?", edit_doc_project_path(@doc, @project) %>

</div>